# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 50, 47, 13))
        self.label.setObjectName("label")
        self.statusCombo = QtWidgets.QComboBox(self.centralwidget)
        self.statusCombo.setGeometry(QtCore.QRect(280, 240, 91, 22))
        self.statusCombo.setObjectName("statusCombo")
        self.seqSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.seqSpin.setGeometry(QtCore.QRect(280, 90, 51, 22))
        self.seqSpin.setObjectName("seqSpin")
        self.newTrackButton = QtWidgets.QPushButton(self.centralwidget)
        self.newTrackButton.setGeometry(QtCore.QRect(430, 20, 75, 23))
        self.newTrackButton.setObjectName("newTrackButton")
        self.description = QtWidgets.QLineEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(280, 140, 201, 20))
        self.description.setObjectName("description")
        self.author = QtWidgets.QLineEdit(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(280, 190, 113, 20))
        self.author.setObjectName("author")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 90, 91, 16))
        self.label_3.setObjectName("label_3")
        self.trackListCombo = QtWidgets.QComboBox(self.centralwidget)
        self.trackListCombo.setGeometry(QtCore.QRect(20, 20, 321, 22))
        self.trackListCombo.setObjectName("trackListCombo")
        self.revSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.revSpin.setGeometry(QtCore.QRect(430, 90, 42, 22))
        self.revSpin.setObjectName("revSpin")
        self.sizeCombo = QtWidgets.QComboBox(self.centralwidget)
        self.sizeCombo.setGeometry(QtCore.QRect(400, 50, 51, 22))
        self.sizeCombo.setObjectName("sizeCombo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 170, 47, 13))
        self.label_6.setObjectName("label_6")
        self.disciplineCombo = QtWidgets.QComboBox(self.centralwidget)
        self.disciplineCombo.setGeometry(QtCore.QRect(280, 50, 51, 22))
        self.disciplineCombo.setObjectName("disciplineCombo")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.fileTree = QtWidgets.QTreeView(self.centralwidget)
        self.fileTree.setGeometry(QtCore.QRect(15, 50, 251, 381))
        self.fileTree.setObjectName("fileTree")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 120, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 220, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Discipline"))
        self.newTrackButton.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Document number"))
        self.label_6.setText(_translate("MainWindow", "Author"))
        self.label_4.setText(_translate("MainWindow", "Rev"))
        self.label_5.setText(_translate("MainWindow", "Description"))
        self.label_7.setText(_translate("MainWindow", "Status"))
        self.label_2.setText(_translate("MainWindow", "Size"))

